In [1]:
import numpy as np

Import is almost always the first thing you do using array. 
It is important we select the environment that has numpy inside otherwise we get an error.
Numpy array is basically a list, possibly written in C, and is much much faster than a python
list. 


In [2]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [4]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [6]:
d = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
d

array([[[2, 3],
        [4, 5]],

       [[6, 2],
        [3, 5]]])

In [7]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum()) # Sum the array
print(e.min()) # Find the minimum value in an array
print(e.max()) # Find the maximum value in an array
print(e.mean()) # Find the arithmetic mean of an array

21
1
6
3.5


In [9]:
print(np.zeros(5)) # Creates an array of zeros with 5 elements
print(np.linspace(0, 6, 10)) # Creates an array of values from 0 through 6 in 10 even spaces
print(np.random.rand(3)) # Three random values between 0 and 1
print(np.random.randint(1, 1000)) # A random integer between 1 and 1000
print(np.arange(25)) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.5725497  0.18694222 0.77442102]
751
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Pandas is where the meat and potatotes of this course is. By getting to know this functions above and in basic_python_datatypes file you
can do a lot of data analysis work. What you will be doing is applying this data analysis techniques to a library called pandas.
Pandas stands for panel data, it is a library in pyhton build on C that is designed to help you quickly explore, cleanup, transform, 
export data that is in a tabular format, also known as structured data. 